export const events = [
  {
    slug: "react-conf-2024",
    image: "/images/event1.png",
    title: "React Conf 2024",
    location: "Nairobi, Kenya",
    date: "March 15, 2024",
    time: "9:00 AM - 6:00 PM (EAT)",
  },
  {
    slug: "nextjs-summit",
    image: "/images/event2.png",
    title: "Next.js Summit",
    location: "Nairobi, Kenya",
    date: "April 22, 2024",
    time: "10:00 AM - 5:00 PM (EAT)",
  },
  {
    slug: "javascript-world",
    image: "/images/event3.png",
    title: "JavaScript World Conference",
    location: "Mombasa, Kenya",
    date: "May 8, 2024",
    time: "8:30 AM - 7:00 PM (EAT)",
  },
  {
    slug: "ai-hackathon-2024",
    image: "/images/event4.png",
    title: "AI Innovation Hackathon",
    location: "Nairobi, Kenya",
    date: "June 14–16, 2024",
    time: "48 Hours (EAT)",
  },
  {
    slug: "web3-developer-meetup",
    image: "/images/event5.png",
    title: "Web3 Developer Meetup",
    location: "Nairobi, Kenya",
    date: "July 20, 2024",
    time: "6:00 PM - 9:00 PM (EAT)",
  },
  {
    slug: "fullstack-conference",
    image: "/images/event6.png",
    title: "Full Stack Conference",
    location: "Eldoret, Kenya",
    date: "August 12, 2024",
    time: "9:00 AM - 6:00 PM (EAT)",
  },
  {
    slug: "devops-unleashed",
    image: "/images/event1.png",
    title: "DevOps Unleashed",
    location: "Nakuru, Kenya",
    date: "September 5, 2024",
    time: "8:00 AM - 5:30 PM (EAT)",
  },
  {
    slug: "mobile-dev-summit",
    image: "/images/event2.png",
    title: "Mobile Development Summit",
    location: "Nairobi, Kenya",
    date: "October 18, 2024",
    time: "9:30 AM - 6:00 PM (EAT)",
  },
  {
    slug: "cybersecurity-conference",
    image: "/images/event3.png",
    title: "Cybersecurity Conference",
    location: "Thika, Kenya",
    date: "November 2, 2024",
    time: "8:00 AM - 7:00 PM (EAT)",
  },
  {
    slug: "data-science-hackathon",
    image: "/images/event4.png",
    title: "Data Science Hackathon",
    location: "Kisumu, Kenya",
    date: "December 7–9, 2024",
    time: "72 Hours (EAT)",
  },
  {
    slug: "cloud-native-meetup",
    image: "/images/event5.png",
    title: "Cloud Native Meetup",
    location: "Nairobi, Kenya",
    date: "January 15, 2025",
    time: "6:30 PM - 9:00 PM (EAT)",
  },
  {
    slug: "frontend-masters",
    image: "/images/event6.png",
    title: "Frontend Masters Conference",
    location: "Nairobi, Kenya",
    date: "February 28, 2025",
    time: "9:00 AM - 5:00 PM (EAT)",
  },
];
